### ISSUE TITLE
Zabbix support 6.0 and 7.0

### ISSUE THREAD

**Issue by sbardeev** [i-ky/effluence#21]
Will it support Zabbix 6.0 and 7.0?

I installed it on Zabbix 6.4.4.
Zabbix service is running, but the data has not appeared in the InfluxDB database.

**Comment by sbardeev** [comment]
Data will send
![image](https://github.com/i-ky/effluence/assets/112647143/54481565-1567-4524-b7e6-a7c7e59c2260)

But series not available
![image](https://github.com/i-ky/effluence/assets/112647143/1ffdaeed-8f23-45ce-ae47-e42cf4baf22b)

I'm using a simple configuration
![image](https://github.com/i-ky/effluence/assets/112647143/d8c0e929-3b59-4134-ae32-dec146fa1b34)

**Comment by i-ky** [comment]
@sbardeev, thank you for the interest in this module!

> Will it support Zabbix 6.0 and 7.0?

I don't have a definitive answer to this question. I don't know any reason why it shouldn't work with latest versions of Zabbix, so it probably should. However, I am not using Zabbix myself, therefore I cannot guarantee it. I developed the module a long time ago and haven't really tested it since then. But judging by git clone stats there are people using it, it is just not clear which versions of Zabbix they are using it with.

> I installed it on Zabbix 6.4.4.

Have you compiled the module yourself or are you using pre-compiled binaries from the release?
Please let me know the version of InfluxDB as well.

> Zabbix service is running, but the data has not appeared in the InfluxDB database.

Do you see any errors in the log file? Is there any traffic flowing to 192.168.22.16:8086?

**Comment by sbardeev** [comment]
May be it doesn't work only for me.

I use pre-compiled binary effluence-v0.1-CentOS-7.6-x64.so.
InfluxDB 1.8.10

I don't see any errors in the logs.
Telnet is working. Grafana successfully connects to InfluxDB data source

**Comment by i-ky** [comment]
> I use pre-compiled binary effluence-v0.1-CentOS-7.6-x64.so.

OK. Since Zabbix is able to load the module there are no obvious compatibility issues.

> InfluxDB 1.8.10

Good. The module was developed and tested in the times when 1.6 (if I recall correctly) was the latest version, so it should work with InfluxDB 1.x without any issues.

> Telnet is working. Grafana successfully connects to InfluxDB data source

This is nice, but kinda irrelevant. Have you tried sniffing with Wireshark/tcpdump?

> May be it doesn't work only for me.

Could you please explain in more detail what you have done and what you expect to happen.

**Comment by i-ky** [comment]
> Data will be exported ![image](https://private-user-images.githubusercontent.com/112647143/303986295-54481565-1567-4524-b7e6-a7c7e59c2260.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTE1MDksIm5iZiI6MTcwNzgxMTIwOSwicGF0aCI6Ii8xMTI2NDcxNDMvMzAzOTg2Mjk1LTU0NDgxNTY1LTE1NjctNDUyNC1iN2U2LWE3YzdlNTljMjI2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODAwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmVlYjFiZTE4ZjY4ZDUwYjdhNzVkNmI4N2Y5YmM5MDc3NmM4OGY5NDU2ZmIzMjYzYzMwMjhiMTU4NGE2Yzg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6_tw6lpfuJpMTgei63ihsm0Rp-AARgDBnhaBHhgiRlY)

These messages mean that module is able to read the configuration file. There are no obvious issues with your configuration file as well.

> I'm using a simple configuration ![image](https://private-user-images.githubusercontent.com/112647143/303986439-d8c0e929-3b59-4134-ae32-dec146fa1b34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTE1MDksIm5iZiI6MTcwNzgxMTIwOSwicGF0aCI6Ii8xMTI2NDcxNDMvMzAzOTg2NDM5LWQ4YzBlOTI5LTNiNTktNDEzNC1hZTMyLWRlYzE0NmZhMWIzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODAwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzYwYjJkMzQ0NjI3NTc3NjZmZTZiZWY2Y2Y2NjhlNmQ2ZDlmYTQ1OGVmZmQyN2RkMzViOTkwOTZjMThjNjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ATJb_a61e8jqcsUeW6AqJbG6D-8sINvoArftAwd0Kuw)

One question though. Do you expect module to use empty string (`""`) as username and password?

**Comment by i-ky** [comment]
@sbardeev, do you have any update?

**Comment by i-ky** [comment]
@sbardeev, since you are not responding, I am going to close this issue.

Feel free to reopen or create a new one, if you are still experiencing problems.

**Comment by ForPractice-Pritam** [comment]
Yeah I have the same question like how to see if the data is stored in influxDB?
